var num = 0;
console.log('num = 0 = ' + + num);
console.log('num + 2 = ' + + num);
num = num + 2;
console.log(num);
num = num * 3;
console.log('num * 3 = ' + + num);
num = num / 2;
console.log('num / 2 = ' + + num);
num++;
console.log('num++ = ' + + num);
num--;
console.log('num-- = ' + + num);
num += 1;
console.log('num += 1 = ' + + num);
num -= 2;
console.log('num -= 2 = ' + + num);
num *= 3;
console.log('num *= 3 = ' + + num);
num /= 2;
console.log('num /= 2 = ' + + num);
num %= 3;
console.log('num %= 3 = ' + + num);

console.log('num == 1 : ' + (num == 1));
console.log('num === 1 : ' + (num === 1));
console.log('num != 1 : ' + (num != 1));
console.log('num > 1 : ' + (num > 1));
console.log('num < 1 : ' + (num < 1));
console.log('num >= 1 : ' + (num >= 1));
console.log('num <= 1 : ' + (num <= 1));
console.log('true && false : ' + (true && false));
console.log('true || false : ' + (true || false));
console.log('!true : ' + (!true));
